CREATE TABLE Comment (
id INT PRIMARY KEY AUTO_INCREMENT,
Comment VARCHAR(2047) NOT NULL, MemberId VARCHAR(255) NOT NULL, 
boardId INT NOT NULL, inserted TIMESTAMP DEFAULT NOW(),
FOREIGN KEY (memberId) REFERENCES Member(id),
FOREIGN KEY (boardId) REFERENCES Board(id));
desc Comment;

SELECT * FROM Comment;
