CREATE TABLE Board 
(id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(255) NOT NULL, body VARCHAR(2047) NOT NULL, memberId VARCHAR(255) NOT NULL, inserted TIMESTAMP DEFAULT NOW()
);

SELECT * FROM Board;
SELECT * FROM Member;

ALTER TABLE Board ADD FOREIGN KEY (MemberId) REFERENCES Member(id);

SELECT id, title, memberId, inserted FROM Board ORDER BY id DESC;